version: '3'
services:
    server:
        build: './Server'
        ports:
            - '80:80'
        depends_on: 
            - database
    database:
        image: 'mongo'
        container_name: 'DBSA'
        environment: 
            - MONGO_INITDB_DATABASE=dbSA
            - MONGO_INITDB_ROOT_USERNAME=puac
            - MONGO_INITDB_ROOT_PASSWORD=1234
        volumes: 
            - ./DB/init-mongo.js:/docker-entrypoint-initdb.d/init/mongo.js:ro
            - ./DB/mongo-volume:/data/db
        ports:
            - '27017:27017'